name: Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 28dd9d6e-33cd-4328-a3f4-61a99b091ec6
          heroku_app_name: anotherdwbot4
          heroku_email: wuzzumva5l@zod.edu.pl
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          HD_OWNER_ID: ${{secrets.OWNER_ID || '1881720028'}}
          HD_TELEGRAM_API: ${{secrets.TELEGRAM_API || '6537576'}}
          HD_TELEGRAM_HASH: ${{secrets.TELEGRAM_HASH || '2898a38704b58b7bc094d43737dfe0fe'}}
          HD_DATABASE_URL: ${{secrets.DATABASE_URL || 'mongodb+srv://abcd:abcd@personalproject.mxx6dgi.mongodb.net/?retryWrites=true&w=majority'}}
          HD_BOT_TOKEN: ${{secrets.BOT_TOKEN || '5390569481:AAHi1-ngnr1pgKyZYn_tdtPwlNXERIMpXGM'}}
          
